[package]
name = "lambda-lw-http-router"
version = "0.4.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "A lightweight, type-safe HTTP router for AWS Lambda functions"
repository = "https://github.com/dev7a/serverless-otlp-forwarder/tree/main/packages/rust/lambda-lw-http-router"
documentation = "https://docs.rs/lambda-lw-http-router"
readme = "README.md"
keywords = ["lambda", "aws", "router", "serverless", "api"]
categories = ["web-programming::http-server", "network-programming"]

[dependencies]
# pin versions to publish
lambda-lw-http-router-core.workspace = { version = "0.4.0" }
lambda-lw-http-router-macro.workspace = { version = "0.4.0" } 
ctor.workspace = true

[dev-dependencies]
lambda_runtime.workspace = true
aws_lambda_events.workspace = true
serde_json.workspace = true
tower.workspace = true
tokio.workspace = true
tokio-test.workspace = true
doc-comment.workspace = true

[package.metadata.cargo-machete]
ignored = ["ctor"]