version = 0.1
[default.build.parameters]
build_in_source = true

[default.deploy.parameters]
stack_name = "kinesis-extension"
resolve_s3 = true
s3_prefix = "kinesis-extension"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
