version = 0.1

[default.global.parameters]
stack_name = "otlp-stdout-logs-processor"
beta_features = "yes"

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "otlp-stdout-logs-processor"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "CollectorsSecretsKeyPrefix=serverless-otlp-forwarder/keys",
  "CollectorsCacheTtlSeconds=300",
  "RouteAllLogs=yes",
  "VpcId=",
  "SubnetIds="
]
image_repositories = []
confirm_changeset = true
