AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Main stack for serverless-otlp-forwarder for SAM deployment

Parameters:
  CollectorsSecretsKeyPrefix:
    Type: String
    Description: The prefix for the secrets manager key for the collector.
    Default: "serverless-otlp-forwarder/keys"
  CollectorsCacheTtlSeconds:
    Type: Number
    Description: TTL in seconds for the collectors configuration cache
    Default: 300
  RouteAllLogs:
    Type: String
    Default: yes
    Description: Route all AWS logs to the Lambda function
  VpcId:
    Type: String
    Description: (Optional) VPC ID for VPC deployment
    Default: ""
  SubnetIds:
    Type: CommaDelimitedList
    Description: (Optional) List of subnet IDs for VPC deployment
    Default: ""

Conditions:
  RouteAllLogs: !Equals [!Ref RouteAllLogs, "yes"]
  HasVpcConfig: !Not [!Equals [!Ref VpcId, ""]]

Resources:
  LogsProcessorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: stdout_processor
    Properties:
      FunctionName: !Ref AWS::StackName
      Description: !Sub "Processes logs from AWS Account ${AWS::AccountId}"
      CodeUri: processor/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64
      Timeout: 60
      LoggingConfig:
        LogFormat: JSON
        ApplicationLogLevel: INFO
        SystemLogLevel: INFO
      Environment:
        Variables:
          OTEL_EXPORTER_OTLP_ENDPOINT: !Sub "{{resolve:secretsmanager:${CollectorsSecretsKeyPrefix}/default:SecretString:endpoint}}"
          OTEL_EXPORTER_OTLP_HEADERS: !Sub "{{resolve:secretsmanager:${CollectorsSecretsKeyPrefix}/default:SecretString:auth}}"
          OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
          COLLECTORS_CACHE_TTL_SECONDS: !Ref CollectorsCacheTtlSeconds
          COLLECTORS_SECRETS_KEY_PREFIX: !Sub "${CollectorsSecretsKeyPrefix}/"
          LAMBDA_EXTENSION_SPAN_PROCESSOR_MODE: async
          LAMBDA_TRACING_ENABLE_FMT_LAYER: false
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "secretsmanager:BatchGetSecretValue"
                - "secretsmanager:ListSecrets"
                - "xray:PutTraceSegments"
                - "xray:PutSpans"
                - "xray:PutSpansForIndexing"
              Resource: "*"
            - Effect: Allow
              Action:
                - "secretsmanager:GetSecretValue"
              Resource: !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CollectorsSecretsKeyPrefix}/*"
      VpcConfig: !If
        - HasVpcConfig
        - SecurityGroupIds:
            - !Ref LogsProcessorSecurityGroup
          SubnetIds: !Ref SubnetIds
        - !Ref AWS::NoValue

  LogsProcessorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: HasVpcConfig
    Properties:
      GroupDescription: Security group for OTLP Logs Processor Lambda
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  LogsProcessorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogsProcessorFunction
      Action: lambda:InvokeFunction
      Principal: logs.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  LogsAccountPolicy:
    Type: AWS::Logs::AccountPolicy
    Condition: RouteAllLogs
    DependsOn:
      - LogsProcessorPermission
    Properties:
      PolicyName: "LambdaSubscriptionPolicy"
      PolicyDocument:
        Fn::Sub: |
          {
            "DestinationArn": "${LogsProcessorFunction.Arn}",
            "FilterPattern": "{ $.__otel_otlp_stdout = * }"
          }
      PolicyType: "SUBSCRIPTION_FILTER_POLICY"
      Scope: "ALL"
      SelectionCriteria: !Sub 'LogGroupName NOT IN ["/aws/${LogsProcessorFunction}"]'

Outputs:
  LogsProcessorFunctionArn:
    Description: ARN of the OTLP stdout processor Lambda function
    Value: !GetAtt LogsProcessorFunction.Arn

  LogsProcessorSecurityGroupId:
    Description: ID of the security group for the Span processor Lambda function
    Condition: HasVpcConfig
    Value: !Ref LogsProcessorSecurityGroup
