[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
aws-config.workspace = true
aws-sdk-lambda = "1.59.0"
http = "1.3.1"

[[bin]]
name = "proxy"
path = "src/main.rs"
