version = 0.1
[default.global.parameters]
beta_features = "true"
stack_name = "todos"

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "todos"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
