[package]
name = "lambda-lw-http-router-core"
version = "0.3.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Core functionality for lambda-lw-http-router"
repository = "https://github.com/dev7a/serverless-otlp-forwarder/tree/main/packages/rust/lambda-lw-http-router/router-core"

[dependencies]
serde_json.workspace = true
lambda_runtime.workspace = true
aws_lambda_events.workspace = true
tracing.workspace = true
opentelemetry.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry-http.workspace = true
lazy_static.workspace = true
ctor.workspace = true
regex.workspace = true

[dev-dependencies]
tokio.workspace = true
http.workspace = true
