version = 0.1

[default.global.parameters]
stack_name = "otlp-stdout-kinesis-processor"
beta_features = "yes"

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "otlp-stdout-kinesis-processor"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "CollectorsSecretsKeyPrefix=serverless-otlp-forwarder/keys",
  "CollectorsCacheTtlSeconds=300",
  "KinesisStreamMode=PROVISIONED",
  "ShardCount=1"
]
image_repositories = []
