default:
  build:
    parameters:
      cached: true
      parallel: false
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      parameter_overrides:
      - CollectorExtensionArn=arn:aws:lambda:us-east-1:961341555982:layer:ocel-arm64-minimal-forwarder-0_128_0-local:8
      - CollectorConfigMapArn=arn:aws:lambda:us-east-1:961341555982:layer:rearset-collector-configmap:16
      - VpcId=""
      - SubnetIds=""
      - RouteAllLogs=true
      - KinesisStreamMode=PROVISIONED
      - ShardCount=1
      region: us-east-1
      resolve_s3: true
      s3_prefix: rearset-kinesis-relay
      stack_name: rearset-kinesis-relay
  global:
    parameters:
      beta_features: true
version: 0.1
