default:
  build:
    parameters:
      cached: true
      parallel: false
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      image_repositories: []
      parameter_overrides:
      - CollectorExtensionArn=arn:aws:lambda:us-east-1:902605180476:layer:ocel-arm64-minimal-forwarder-0_128_0-beta:2
      - CollectorConfigMapArn=arn:aws:lambda:us-east-1:961341555982:layer:rearset-collector-configmap:17
      - VpcId=""
      - SubnetIds=""
      region: us-east-1
      resolve_s3: true
      s3_prefix: rearset-signals-relay
      stack_name: rearset-signals-relay
  global:
    parameters:
      beta_features: true
      stack_name: aws-span-processor
version: 0.1
