AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS SAM template for the lambda-otel-lite example.


Globals:
  Function:
    MemorySize: 128
    Timeout: 30
    Architectures:
      - arm64
    Runtime: nodejs22.x
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: INFO
  

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-handler-example'
      CodeUri: ./handler
      Handler: app.handler
      Description: 'Demo Node Lambda function to showcase OpenTelemetry integration'
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LAMBDA_EXTENSION_SPAN_PROCESSOR_MODE: async
          NODE_OPTIONS: --require @dev7a/lambda-otel-lite/extension # required for async mode

  HelloWorldESBuild:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Format: "cjs"
        Platform: "node"
        EntryPoints: 
          - app.js
          - init.js
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-handler-example-esbuild'
      CodeUri: ./handler
      Handler: app.handler
      Description: 'Demo Node Lambda function to showcase OpenTelemetry integration'
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          LAMBDA_EXTENSION_SPAN_PROCESSOR_MODE: async
          NODE_OPTIONS: --require /var/task/init.js # required for async mode

Outputs:
  HelloWorldFunctionUrl:
    Description: 'URL of the Demo Hello World Lambda function'
    Value: !GetAtt HelloWorldUrl.FunctionUrl
  HelloWorldESBuildFunctionUrl:
    Description: 'URL of the Demo Hello World Lambda function'
    Value: !GetAtt HelloWorldESBuildUrl.FunctionUrl
