version = 0.1
[default.global.parameters]
stack_name = "otel-demo"
beta_features = "yes"

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "otel-demo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ExporterProtocol=\"http/protobuf\" ExporterCompression=\"gzip\""
image_repositories = []
