AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS SAM template for the serverless-otlp-forwarder application.

Parameters:
  ExporterProtocol:
    Type: String
    Description: The protocol of the OTLP exporter
    Default: http/protobuf
  ExporterCompression:
    Type: String
    Description: The compression of the OTLP exporter
    Default: gzip


Globals:
  Function:
    MemorySize: 128
    Timeout: 30
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: WARN
    Environment:
      Variables:
        OTEL_EXPORTER_OTLP_PROTOCOL: !Ref ExporterProtocol
        OTEL_EXPORTER_OTLP_COMPRESSION: !Ref ExporterCompression
  

Resources:
  QuotesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-quotes-queue'
      VisibilityTimeout: 180
      MessageRetentionPeriod: 345600  # 4 days

  BackendApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${AWS::StackName}-api'
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL


  RustHelloLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: hello
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-hello'
      CodeUri: ./rust
      Handler: bootstrap
      Runtime: provided.al2023
      Description: 'Demo Hello Lambda function to showcase OpenTelemetry integration'
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          RUST_LOG: info
          OTEL_SERVICE_NAME: !Sub '${AWS::StackName}-lambda-hello'

  RustSimpleLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: simple
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-simple'
      CodeUri: ./rust
      Handler: bootstrap
      Runtime: provided.al2023
      Description: 'Demo Simple Lambda function to showcase OpenTelemetry integration'
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          RUST_LOG: info
          OTEL_SERVICE_NAME: !Sub '${AWS::StackName}-lambda-simple'

  RustTowerLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: tower
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-tower'
      CodeUri: ./rust
      Handler: bootstrap
      Runtime: provided.al2023
      Description: 'Demo Tower Lambda function to showcase OpenTelemetry integration'
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          OTEL_SERVICE_NAME: !Sub '${AWS::StackName}-lambda-tower'
          AWS_LAMBDA_EXEC_WRAPPER: /var/task/bootstrap

  BackendLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: backend
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-backend'
      CodeUri: ./rust
      Handler: bootstrap
      Runtime: provided.al2023
      Description: 'Demo Backend Lambda function to showcase OpenTelemetry integration'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          RUST_LOG: info
          OTEL_SERVICE_NAME: !Sub '${AWS::StackName}-lambda-backend'
          TABLE_NAME: !Sub '${AWS::StackName}-table'
      Events:
        PostQuote:
          Type: Api
          Properties:
            Path: /quotes
            Method: post
            RestApiId: !Ref BackendApi
        GetQuote:
          Type: Api
          Properties:
            Path: /quotes/{id}
            Method: get
            RestApiId: !Ref BackendApi
        ListQuotes:
          Type: Api
          Properties:
            Path: /quotes
            Method: get
            RestApiId: !Ref BackendApi

  FrontendLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: frontend
    Properties:
      FunctionName: !Sub '${AWS::StackName}-lambda-frontend'
      CodeUri: ./rust
      Handler: bootstrap
      Runtime: provided.al2023
      Description: 'Demo Frontend Lambda function to showcase OpenTelemetry integration'
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          RUST_LOG: info
          OTEL_SERVICE_NAME: !Sub '${AWS::StackName}-lambda-frontend'
          TARGET_URL: !Sub 'https://${BackendApi}.execute-api.${AWS::Region}.amazonaws.com/prod'


  PythonLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-python-client'
      CodeUri: ./python
      Handler: main.lambda_handler
      Runtime: python3.12
      Description: 'Demo Python Client Lambda function to showcase OpenTelemetry integration'
      Environment:
        Variables:
          OTEL_SERVICE_NAME: !Sub '${AWS::StackName}-python-client'
          TARGET_URL: !Sub 'https://${BackendApi}.execute-api.${AWS::Region}.amazonaws.com/prod/quotes'
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt QuotesQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 10

  NodeLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-node-client'
      CodeUri: ./node
      Handler: index.handler
      Runtime: nodejs20.x
      Description: 'Demo Node.js Client Lambda function to showcase OpenTelemetry integration'
      Environment:
        Variables:
          OTEL_SERVICE_NAME: !Sub '${AWS::StackName}-node-client'
          TARGET_URL: !Sub 'https://${BackendApi}.execute-api.${AWS::Region}.amazonaws.com/prod/quotes'
          QUOTES_QUEUE_URL: !Ref QuotesQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt QuotesQueue.QueueName
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: "Trigger the Lambda function every time period"
            Enabled: true

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-table'
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expiry
        Enabled: true

Outputs:
  FrontendLambdaFunctionArn:
    Description: 'ARN of the Demo Frontend Lambda function'
    Value: !GetAtt FrontendLambdaFunction.Arn
  BackendLambdaFunctionArn:
    Description: 'ARN of the Demo Backend Lambda function'
    Value: !GetAtt BackendLambdaFunction.Arn
  PythonLambdaFunctionArn:
    Description: 'ARN of the Demo Python Client Lambda function'
    Value: !GetAtt PythonLambdaFunction.Arn
  BackendUrl:
    Description: 'URL of the Backend API'
    Value: !Sub 'https://${BackendApi}.execute-api.${AWS::Region}.amazonaws.com/prod/quotes'
  FrontendUrl:
    Description: 'URL of the Frontend Lambda function'
    Value: !GetAtt FrontendLambdaFunctionUrl.FunctionUrl
  HelloWorldUrl:
    Description: 'URL of the Hello World Lambda function'
    Value: !Sub '${RustHelloLambdaFunctionUrl.FunctionUrl}hello/world'
  SimpleUrl:
    Description: 'URL of the Simple Lambda function'
    Value: !Sub '${RustSimpleLambdaFunctionUrl.FunctionUrl}'
  TowerUrl:
    Description: 'URL of the Tower Lambda function'
    Value: !Sub '${RustTowerLambdaFunctionUrl.FunctionUrl}'
