name: Publish livetrace CLI

on:
  push:
    branches:
      - main
    paths:
      - 'cli/livetrace/**'
  workflow_dispatch:

permissions:
  contents: write # Needed to allow reusable workflow to push tags

jobs:
  publish_livetrace_crate:
    name: Publish livetrace to Crates.io and Tag
    uses: ./.github/workflows/reusable-publish-rust-crate.yml
    with:
      crate_name: "livetrace"
      crate_path: "cli/livetrace"
      manifest_path: "cli/livetrace/Cargo.toml"
      tag_prefix: "cli/livetrace-v"
      cargo_token_secret_name: "CARGO_REGISTRY_TOKEN" # Using the common secret
      test_features: "" # livetrace does not have specific features listed for this
    secrets: inherit # Pass down secrets like CARGO_REGISTRY_TOKEN

  create_github_release_livetrace:
    name: Create GitHub Release for livetrace
    needs: publish_livetrace_crate
    if: needs.publish_livetrace_crate.outputs.needs_publish == 'true'
    uses: ./.github/workflows/reusable-release-cli.yml
    with:
      cli_name: "livetrace"
      manifest_path: "cli/livetrace/Cargo.toml"
      binary_name: "livetrace"
      tag_name: ${{ needs.publish_livetrace_crate.outputs.tag_name }}
      build_features: "" # Consistent with test_features for livetrace
      release_notes_file_path: "cli/livetrace/RELEASE_NOTES.md"
    secrets: inherit
