name: Publish Python Lambda OTel Lite

on:
  # Trigger on PRs that touch the Python package
  pull_request:
    paths:
      - 'packages/python/lambda_otel_lite/**'
    types: [opened, synchronize]
  # Trigger on merges to main that touch the Python package
  push:
    branches:
      - main
    paths:
      - 'packages/python/lambda_otel_lite/**'

# Add permissions needed for the workflow
permissions:
  contents: write  # Needed for pushing tags
  id-token: write # Needed for publishing to PyPI

jobs:
  test:
    strategy:
      matrix:
        include:
          # x64 runner
          - os: ubuntu-latest
            arch: x64
            python-version: '3.12'
          # arm64 runner
          - os: ubuntu-22.04-arm
            arch: arm64
            python-version: '3.12'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: packages/python/lambda_otel_lite

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine ruff mypy pytest pytest-cov toml
          pip install -e ".[dev]"

      - name: Run quality checks
        run: |
          ruff check --isolated src/lambda_otel_lite tests
          ruff format --check --isolated src/lambda_otel_lite tests
          mypy src/lambda_otel_lite
          pytest

  publish:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: pypi
    defaults:
      run:
        working-directory: packages/python/lambda_otel_lite

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine ruff mypy pytest pytest-cov toml
          pip install -e ".[dev]"

      - name: Build package
        run: python -m build

      - name: Verify package version
        run: |
          PACKAGE_VERSION=$(python -c "import sys; sys.path.insert(0, 'src'); from lambda_otel_lite import __version__; print(__version__)")
          if git tag -l | grep -q "python-v$PACKAGE_VERSION"; then
            echo "Version $PACKAGE_VERSION already published"
            exit 1
          fi
          echo "Publishing version $PACKAGE_VERSION"

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

      - name: Create and push tag
        run: |
          PACKAGE_VERSION=$(python -c "import sys; sys.path.insert(0, 'src'); from lambda_otel_lite import __version__; print(__version__)")
          git tag "python-v$PACKAGE_VERSION"
          git push origin "python-v$PACKAGE_VERSION" 