name: Publish Node Lambda OTel Lite

on:
  # Trigger on PRs that touch the Node.js package
  pull_request:
    paths:
      - 'packages/node/lambda-otel-lite/**'
    types: [opened, synchronize]
  # Trigger on merges to main that touch the Node.js package
  push:
    branches:
      - main
    paths:
      - 'packages/node/lambda-otel-lite/**'

# Add permissions needed for the workflow
permissions:
  contents: write  # Needed for pushing tags
  id-token: write # Needed for publishing to npm

jobs:
  test:
    strategy:
      matrix:
        include:
          # x64 runner
          - os: ubuntu-latest
            arch: x64
            node-version: '18'
          # arm64 runner
          - os: ubuntu-22.04-arm
            arch: arm64
            node-version: '18'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: packages/node/lambda-otel-lite

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.arch }}
          cache: 'npm'
          cache-dependency-path: packages/node/lambda-otel-lite/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: |
          npm run lint
          npm test
          npm run build

  publish:
    needs: test
    # Only run on pushes to main, never on PRs
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/node/lambda-otel-lite

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          architecture: x64
          cache: 'npm'
          cache-dependency-path: packages/node/lambda-otel-lite/package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Verify package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          VERSION_TS_VERSION=$(grep -o "'[0-9]\+\.[0-9]\+\.[0-9]\+'" src/version.ts | tr -d "'")
          
          if [ "$PACKAGE_VERSION" != "$VERSION_TS_VERSION" ]; then
            echo "Version mismatch: package.json ($PACKAGE_VERSION) != version.ts ($VERSION_TS_VERSION)"
            exit 1
          fi
          
          if git tag -l | grep -q "node-v$PACKAGE_VERSION"; then
            echo "Version $PACKAGE_VERSION already published"
            exit 1
          fi
          echo "Publishing version $PACKAGE_VERSION"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Create and push tag
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          git tag "node-v$PACKAGE_VERSION"
          git push origin "node-v$PACKAGE_VERSION" 