name: Publish startled CLI

on:
  push:
    branches:
      - main
    paths:
      - 'cli/startled/**'
  workflow_dispatch:

permissions:
  contents: write # Needed to allow reusable workflow to push tags

jobs:
  publish_startled_crate:
    name: Publish startled to Crates.io and Tag
    uses: ./.github/workflows/reusable-publish-rust-crate.yml
    with:
      crate_name: "startled"
      crate_path: "cli/startled"
      manifest_path: "cli/startled/Cargo.toml"
      tag_prefix: "cli/startled-v"
      cargo_token_secret_name: "CARGO_REGISTRY_TOKEN" # Using the common secret
      test_features: "screenshots" # startled has a 'screenshots' feature
    secrets: inherit # Pass down secrets like CARGO_REGISTRY_TOKEN

  create_github_release:
    name: Create GitHub Release for startled
    needs: publish_startled_crate
    if: needs.publish_startled_crate.outputs.needs_publish == 'true'
    uses: ./.github/workflows/reusable-release-cli.yml
    with:
      cli_name: "startled"
      manifest_path: "cli/startled/Cargo.toml"
      binary_name: "startled"
      tag_name: ${{ needs.publish_startled_crate.outputs.tag_name }}
      build_features: "screenshots"
      release_notes_file_path: "cli/startled/RELEASE_NOTES.md"
    secrets: inherit
