# .github/workflows/release-livetrace.yml
name: Release livetrace CLI

on:
  push:
    tags:
      - 'cli/livetrace-v*'

jobs:
  release_cli:
    name: Build and Release livetrace
    permissions:
      contents: write # Grant write permission for contents to this job
    uses: ./.github/workflows/reusable-release-cli.yml
    with:
      cli_name: "livetrace"
      manifest_path: "cli/livetrace/Cargo.toml"
      binary_name: "livetrace"
      tag_name: ${{ github.ref_name }}
      # build_features: "" # Default is empty, explicitly shown for clarity
      release_notes_file_path: "cli/livetrace/RELEASE_NOTES.md"
    secrets: inherit
