# .github/workflows/release-startled.yml
name: Release startled CLI

on:
  push:
    tags:
      - 'cli/startled-v*'

jobs:
  release_cli:
    name: Build and Release startled
    # IMPORTANT: The reusable workflow must exist on the 'main' branch (or the specified ref)
    # for this 'uses' directive to be valid during a real workflow run.
    # A linter might show an error if 'reusable-release-cli.yml' is not yet on 'main'.
    uses: ./.github/workflows/reusable-release-cli.yml@main # Pin to a specific SHA/tag for stability in production
    with:
      cli_name: "startled"
      manifest_path: "cli/startled/Cargo.toml"
      binary_name: "startled"
      tag_name: ${{ github.ref_name }}
      build_features: "screenshots"
    secrets: inherit
